apiVersion: apps/v1
kind: Deployment
metadata:
  name: veritrans-deployment
  labels:
    app: veritrans
spec:
  replicas: 4
  selector:
    matchLabels:
      app: veritrans
  template:
    metadata:
      labels:
        app: veritrans
    spec:
      containers:
      - name: veritrans-service
        image: metalgear121/veritrans-service:v1.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: veritrans
  labels:
    app: veritrans
spec:
  type: NodePort
  selector:
    app: veritrans
  ports:
  - port: 8080
    targetPort: 8080
